### ISSUE TITLE
Update up-core-api/uprotocol/uri.proto to make microuri mandatory and longuri optional.

### ISSUE THREAD

**Issue by ruchirchauhan** [eclipse-uprotocol/up-spec#102]
@stevenhartley, as per our discussion earlier, I think we need to update uri.proto to support mandatory micro and optional long uri formats. 

Proposed change:
1. UEntity. name = currently is required field, should become optional
2. UEntity.id = currently is optional field, should become required
3. UEntity.version_major/minor = currently optional, Not sure, do we need to update these too, may be not ?
4. UResource.name = currently is required field, should become optional
5. UResource.instance = Not sure ?
6. UResource.id = currently is optional field, should become required

Note: There is a check corresponding to UResource.name in up-client-zenoh-cpp, which checks for its value to be "rpc", for rpc type messages. Are we planning on doing that still ? If yes then, may be we can't make longuri optional ans that requires UResource.name to be present, thoughts ?

**Comment by stevenhartley** [comment]
Hi @ruchirchauhan ,
I agree with your proposed changes (for 5 it should be optional). Could you make the corresponding change in up-spec now that I merged up-core-api ?

**Comment by sophokles73** [comment]
Based on the changes proposed here (and implemented in #110 already), we also need to change the [UUri specification](https://github.com/eclipse-uprotocol/up-spec/blob/main/basics/uri.adoc#3-validators) as well. Actually, IMHO we should remove the whole section from the UUri spec and instead add corresponding informtation to the other documents where we actually require UUris to contain certain information, e.g. in a the context of UTransport, where a UUri needs to be resolved. I had already created https://github.com/eclipse-uprotocol/up-rust/issues/78 because the current validation is too restrictive/inappropriate for certain use cases.

@stevenhartley @PLeVasseur WDYT?

**Comment by stevenhartley** [comment]
@sophokles73 agree.

**Comment by evshary** [comment]
I guess short-form UUri can always be transformed from micro-form UUri, right?
Want to make sure we don't need to make sure the UUri is short-form in up-client-zenoh.

> Note: There is a check corresponding to UResource.name in up-client-zenoh-cpp, which checks for its value to be "rpc", for rpc type messages. Are we planning on doing that still ? If yes then, may be we can't make longuri optional ans that requires UResource.name to be present, thoughts ?

There should be a way to check RPC type messages in micro-form UUri. (id < 0x800)
https://github.com/eclipse-uprotocol/up-spec/blob/main/basics/uri.adoc#3-validators
![image](https://github.com/eclipse-uprotocol/up-spec/assets/456210/d351e866-cb6a-4957-83e6-abb19b66207c)

**Comment by evshary** [comment]
IMHO, I think keeping a central place for UUri is easier to find (at least for me). Maybe we can put the definition how UUri is valid in the places where it applies, and then link these to a central document.
For the newcomer, they can know: oh, there are three kinds of UUri, and here are the links to how they are used/validated in uProtocol.

**Comment by stevenhartley** [comment]
Closing this issue as we will address all ourstanding URI topics with #120
