### ISSUE TITLE
Removal of UAuthority id & ip

### ISSUE THREAD

**Issue by stevenhartley** [eclipse-uprotocol/up-spec#115]
**ISSUE SHIFTING TO DROPPING IP and ID**

The purpose of UAuthority.name was to holds the [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986#section-3.2) UAuthority containing username, hostname, and port notation.

UAuthority.number.ip purpose was to hold the IP address in 4 byte (IPv4) or 16 byte (IPv6) notation.

UAuthority.number.id purpose was to contain a simple id that could be used in micro form (i.e. fit into 255 bytes) 
UAuthority's id property is [defined as a byte array](https://github.com/eclipse-uprotocol/up-spec/blob/8fcb37da046193599aa961a78f05af4eedb90025/up-core-api/uprotocol/uri.proto#L63) without any further assumptions regarding its semantics nor encoding. [ShortUriSerializer](https://github.com/eclipse-uprotocol/up-java/blob/90c3e1ed9b80ca03629b3ecba41f99fb3e2a5e69/src/main/java/org/eclipse/uprotocol/uri/serializer/ShortUriSerializer.java#L80) assumes that the bytes in the array actually represent a UTF8 encoded string but it is not explicitly defined as such. 

The following PR shall be used to explicitly set the format of ID to be UTF8 by changing the type from byte to string.

Additionally, there are no explicit guidelines for how to represent the IP address in string form so the recommendation will be to update the uri spec to state that it MUST follow [rfc5952](https://www.rfc-editor.org/rfc/rfc5952)

**Comment by sophokles73** [comment]
> The purpose of UAuthority.name was to holds the [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986#section-3.2) UAuthority containing username, hostname, and port notation.

I was not aware of the fact that it should also hold userinfo and port. How does that work when using IP addresses? Is the userinfo and port irrelevant in that case?

My understanding was (and is) that UAutority can contain a [URI _host_](https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.2) only, but not a port nor userinfo ...

**Comment by sophokles73** [comment]
I guess my point is that UAuthority, the way it is currently specified, _could_ only contain userinfo and/or port in its `name` property but there is no way of storing neither userinfo nor port in either `ip` or `id`.

FMPOV the spec therefore needs to be changed to explicitly rule out the inclusion of userinfo and/or port in the `name`.

**Comment by sophokles73** [comment]
Here's another thought:
I have a hard time seeing a use case that would actually require having an IP address or a (separate) ID at all as the authority. When a uEntity wants to send a request or notification, or publish an event, it should be fine with only using (logical) names in the authority of UUris. The only place where the IP address becomes relevant, is when a UTransport implementation needs to connect to the underlying communication infrastructure in order to send the message via an IP based network. However, that IP address is not necessarily the IP address from a UMessage's sink (or source) but will most likely be determined through configuration properties etc.

The routing logic in the UStreamer can be based on name-only authorities as well, I believe. The routing happens based on the UUris in the UMessages, not the IP addresses of the message brokers being used to transport the messages.

I therefore think that it should be possible to remove all but the (logical) name from UAuthority and let the UTransports resolve concrete IP addresses using arbitrary mechanisms, when needed. The identifiers in UEntity and UResource still make sense, even if only for addressing MCU resources via SOME/IP.

**Comment by sfactor33** [comment]
Streamers seem like the logic place to have the awareness of their domain's physical connections and thus local IP addresses.  If they would need to do those lookups regularly, probably best that the streamers maintain and persist that kind of routing information.

**Comment by stevenhartley** [comment]
@sophokles73 and I discussed this further after the uProtocol meeting today. I agree that adding ip and id was an artifact of micro URI however it has caused us to go off into the weeds. IP address is only used in SOME/IP and the mapping of name to number can be done at the very end through very efficient lookups to static IP address tables (since IP addresses will most likely be fixed). We can encode the name inside of a micro URI (UTF-8 format) so long as it fits within the limit set. 

As a result this issue is now pivoting to dropping the ip and id from UAuthority (it wasn't there in 1.3.6 production version of uProtocol as well).

**Comment by sophokles73** [comment]
Sounds good to me :-) If the 255 byte limit is of great concern, we could also use a _smarter_ length field, e.g. using the MSB to indicate that the length actually uses 2 bytes instead if one or something like that.

If we agree to remove `id` and `ip` from authority, would it then make sense to move `UAuthority.name` to `UUri.authority` and remove the UAuthority type altogether?

**Comment by stevenhartley** [comment]
> Sounds good to me :-) If the 255 byte limit is of great concern, we could also use a _smarter_ length field, e.g. using the MSB to indicate that the length actually uses 2 bytes instead if one or something like that.
> 
> If we agree to remove `id` and `ip` from authority, would it then make sense to move `UAuthority.name` to `UUri.authority` and remove the UAuthority type altogether?

No, I would like to keep name in UAuthority incase we need more info later and to make it more inline with 1.3.6 version of UUri. @sophokles73 will you incorporate these changes in your uri.adoc update? I'll code later today hopefully this in Java so I can see how much of an impact this is.

**Comment by stevenhartley** [comment]
Topic being covered now by #121
