### ISSUE TITLE
uP-L2: UURI requirements clarification 

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-spec#42]
I'm a bit unclear on if the RpcClient, RpcServer should have stronger requirements on the UURIs they are given so that they are resolved.

It appears like it should be the case for [uP-L1](https://github.com/eclipse-uprotocol/uprotocol-spec/blob/main/basics/uri.adoc#72-utransports-up-l1) and [uP-L3](https://github.com/eclipse-uprotocol/uprotocol-spec/blob/main/basics/uri.adoc#71-application-layer-up-l3-ues) based on my reading of the UURI spec.

However uP-L2 is not mentioned in the same section.

Further when I check on the section about implementing RpcClient, the [requirements look a bit looser on the UURI](https://github.com/eclipse-uprotocol/uprotocol-spec/blob/main/up-l2/rpcclient.adoc#3-implementation):
```
MUST return INVALID_PARAMETER for the following errors:
* UUri is null or empty
```

So I'm a bit unclear.

Is uP-L2 communication somehow different and can use unresolved UURIs? Is the uLink library supposed to fill in any missing details with uDiscovery? Or should the UURI also need to be resolved for uP-L2 comms?

**Comment by PLeVasseur** [comment]
By the way, I thought about this when reading the [PR adding in support for uP-L2](https://github.com/ZettaScaleLabs/uprotocol-rust-ulink-zenoh/pull/2/files#r1442139810) for `uprotocol-rust-ulink-zenoh`.

**Comment by evshary** [comment]
I also want to check the timing of resolving UURI.
To resolve the UURI, we need both micro and long forms to be satisfied.
However, if users only want to use the long form (Name), should they always need to create the short form (ID) every time?

To take a step further, what is the best practice to generate ID? Should Users fill in a random number by themselves? Perhaps we could generate the ID automatically while users create the long form since most users might feel intuitive about creating UURI with a name.

**Comment by stevenhartley** [comment]
We discussed this at the uProtocol-zenoh weekly sync up. L3 defines the format they want in their service contracts (ex. passing UUri object, string, bytes, etc...). The uP-L1/L2 contract (the interfaces defined in the language SDKs) are UUri objects that could hold both names and numbers, moving forward we are saying (uTransport spec will be clarified):

- UUri **MUST** contain numbers
- UUri **SHOULD** contain names

The justification for this is to support transports that only work in numbers like SOME/IP.
